More detailed instruction to get going with Docker
mermaid-js/mermaid-cli pull request #105
Opened 2021-03-04 16:00 UTC by dwvisser

I had a hard time initially with trying out the container, because it wasn't documented on hub.docker.com how to use it. This will hopefully remedy that for others.

## :bookmark_tabs: Summary

I describe the simplest use of having a diagram defined in a text file, and how to use the Docker container to process it. I couldn't find a conventional file extension for "mermaid files", so I chose .mmd. Feel free to modify.

I didn't create an issue tracker. I hope that's OK.

2021-03-04 17:49 UTC, sidharthv96 requested changes

2021-03-04 17:49 UTC, sidharthv96 commented on README.md
> +The container looks for input files in `/data`. So for example, if you have a diagram defined on your system in `/path/to/diagrams/diagram.mmd`, you can use the container generate an SVG file as foll
```suggestion
The container looks for input files in `/data`. So for example, if you have a diagram defined on your system in `/path/to/diagrams/diagram.mmd`, you can use the container to generate an SVG file as follows:
```

2021-03-08 07:29 UTC, MindaugasLaganeckas commented
@dwvisser : thank you very much for your PR! :) Please, address the review feedback and I will merge PR ASAP :)

Have a very nice day!

2021-03-08 07:41 UTC, sidharthv96 approved these changes

2021-03-08 09:43 UTC, merged