feature: add option to define output format
mermaid-js/mermaid-cli pull request #382
Opened 2022-09-14 16:39 UTC by root360-AndreasUlm

Signed-off-by: Andreas Ulm <andreas.ulm@skaylink.com>

## :bookmark_tabs: Summary

This commit adds the short option `-e` and the long option `--outputFormat` to overwrite the output format of images generated when handling markdown files.

Resolves #248 

## :straight_ruler: Design Decisions

The option defines a variable called outputFormat.
The variable is given to `run()` function and used instead of `path.extname(output).replace('.', '')` when calling `parseMMD()`.
The value is given via CLI argument or falls back to `path.extname(output).replace('.', ''),` and in case of markdown extension to 'svg' to keep current behaviour.

## :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid-cli/blob/master/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [ ] :bookmark: targeted `master` branch

2022-09-14 16:41 UTC, root360-AndreasUlm commented
FYI: to run the test suite on my MacBook Pro M1 I had to increase the timeout by using:
```
yarn node --experimental-vm-modules $(yarn bin jest) --testTimeout 20000
```

2022-09-14 17:23 UTC, aloisklink requested changes
Great PR! Thanks for adding some great tests too!

Most of my review comments are minor.

The only important one is: can you move the default `outputFormat` checks out of the `cli()` function and into the `run()` function?
(we'll also need to change the `error()` call to instead `throw new Error(...)`)

That way we should be backwards compatible with anybody already using the `run()` function.

2022-09-14 17:23 UTC, aloisklink commented on src/index.js
>   * @param {boolean} [opts.quiet] - If set, suppress log output.
Assuming you move the default `outputFormat` logic into this `run()` function, we can use this doc string.

```suggestion
 * @param {boolean} [opts.quiet] - If set, suppress log output.
 * @param {"svg" | "png" | "pdf"} [opts.outputFormat] - Mermaid output format.
 * Defaults to `output` extension. Overrides `output` extension if set.
```

2022-09-14 17:23 UTC, aloisklink commented on src/index.js
> +  }
Can you move this into the `run()` function?

This library exposes the `run()` function, so we should move this default behavior into that function to maintain backwards compatibility (even if it's a bit slower).

We'd also need to change the error condition to `throw new Error('Output format must be one of "svg", "png" or "pdf"');`

2022-09-14 20:43 UTC, aloisklink approved these changes
Awesome! Thanks for the changes. It all looks great to me, but I'll let @MindaugasLaganeckas do a final review before merging, in case there's anything I missed.

2022-09-14 20:43 UTC, aloisklink commented on src-test/test.js
> +      // files should exist, and they should be SVGs
Fixed in https://github.com/mermaid-js/mermaid-cli/pull/382/commits/fa79772dedda70470830ad2af17b0e25b5c89a7a

2022-09-14 20:44 UTC, aloisklink commented on src-test/test.js
> +        expect(pngFile).toMatch(/^.*PNG/)
Fixed in https://github.com/mermaid-js/mermaid-cli/pull/382/commits/fa79772dedda70470830ad2af17b0e25b5c89a7a

2022-09-14 20:44 UTC, aloisklink commented on src/index.js
>   * @param {boolean} [opts.quiet] - If set, suppress log output.
Fixed in https://github.com/mermaid-js/mermaid-cli/pull/382/commits/fa79772dedda70470830ad2af17b0e25b5c89a7a

2022-09-14 20:44 UTC, aloisklink commented on src/index.js
> +  }
Fixed in https://github.com/mermaid-js/mermaid-cli/pull/382/commits/fa79772dedda70470830ad2af17b0e25b5c89a7a and https://github.com/mermaid-js/mermaid-cli/pull/382/commits/c36859c2cf393e7b5d0cf8b5007c7bdee9e759ee

2022-09-14 20:44 UTC, aloisklink commented on src/index.js
> +        const outputFile = output.replace(/(\.(md|png|svg|pdf))$/, `-${diagrams.length + 1}$1`).replace(/(\.md)$/, '.' + outputFormat)
Fixed in https://github.com/mermaid-js/mermaid-cli/pull/382/commits/fa79772dedda70470830ad2af17b0e25b5c89a7a

2022-09-15 08:47 UTC, MindaugasLaganeckas commented
Thank you for a good PR @root360-AndreasUlm  and very thorough review @aloisklink 😄

2022-09-15 08:47 UTC, merged

2022-10-02 22:53 UTC, ValentinMi commented
Exactly what i needed , thank you